# Lazarus compiler-generated binaries (safe to delete)
find ./ -iname '*.exe' > rmgitignore.txt 
find ./ -iname '*.dll' >> rmgitignore.txt 
find ./ -iname '*.so' >> rmgitignore.txt 
find ./ -iname '*.dylib' >> rmgitignore.txt 
# find ./ -iname '*.lrs é importante
find ./ -iname '*.res' >> rmgitignore.txt 
find ./ -iname '*.compiled' >> rmgitignore.txt 
find ./ -iname '*.dbg' >> rmgitignore.txt 
find ./ -iname '*.ppu' >> rmgitignore.txt 
find ./ -iname '*.o' >> rmgitignore.txt 
find ./ -iname '*.or' >> rmgitignore.txt 
find ./ -iname '*.a' >> rmgitignore.txt 

# Lazarus autogenerated files (duplicated info)
find ./ -iname '*.rst' >> rmgitignore.txt 
find ./ -iname '*.rsj' >> rmgitignore.txt 
find ./ -iname '*.lrt' >> rmgitignore.txt 

# Lazarus local files (user-specific info)
find ./ -iname '*.lps' >> rmgitignore.txt 

# Lazarus backups and unit output folders.
# These can be changed by user in Lazarus/project options.
find ./ -iname 'bin/*' >> rmgitignore.txt 
find ./ -iname 'backup/*' >> rmgitignore.txt 
find ./ -iname 'bak/*' >> rmgitignore.txt 
find ./ -iname 'lib/*' >> rmgitignore.txt 
find ./ -iname 'log/*' >> rmgitignore.txt 
find ./ -iname 'logs/*' >> rmgitignore.txt 
find ./ -iname 'tmp/*' >> rmgitignore.txt 
find ./ -iname 'temp/*' >> rmgitignore.txt 
find ./ -iname 'superado/*' >> rmgitignore.txt 
find ./ -iname '_superado/*' >> rmgitignore.txt 
find ./ -iname 'modules/*' >> rmgitignore.txt 
find ./ -iname '*.bak' >> rmgitignore.txt 

# Application bundle for Mac OS
find ./ -iname '*.app/' >> rmgitignore.txt 
