<!--  Metas Author, e_mail e local -->
<html lang="pt-BR">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=windows-1252">
    <meta name="author" content="Paulo Sérgio da Silva Pacheco">
    <meta name="e_mail" content="paulosspacheco@yahoo.com.br">
    <meta name="local" content="Icaraí - Caucaia - Ceará - Brasil">
  </head>
  <bodY>
    <div class="footer">
      <!-- inicio <div class="footer"> -->
      <p>Versão: 0.208.0</p>
      <table style="width: 100%;">
        <tbody>
          <tr>
            <td style="text-align: right; vertical-align: middle; background-color: white;">Criado
              em:</td>
            <td style="text-align: left; vertical-align: middle; background-color: white;"><span
                id="createDate">meta name="createDate" content="dd/mm/aaaa"</span></td>
            <td style="text-align: right; vertical-align: middle; background-color: white;">Autor:</td>
            <td style="text-align: left; vertical-align: middle; background-color: white;"><span
                id="author">meta name="author" content="Paulo Sérgio da Silva
                Pacheco"</span></td>
          </tr>
          <tr>
            <td style="text-align: right; vertical-align: middle; background-color: white;">Atualizado
              em:</td>
            <td style="text-align: left; vertical-align: middle; background-color: white;"><span
                id="createDateUpdate">meta name="createDateUpdate"
                content="dd/mm/aaaa"</span></td>
            <td style="text-align: right; vertical-align: middle; background-color: white;">Local:</td>
            <td style="text-align: left; vertical-align: middle; background-color: white;">
              <span id="local">meta name="local" content="Icaraí - Caucaia -
                Ceará - Brasil"</span></td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- fim <div class="footer"> -->
   </body>
</html>
