var tipuesearch = {
  pages: [
  {url: "docs/assistant_api_openai /index.html", title: "Assistant API da OpenAI ", text: "", tags: "2021 adquirir agregar após assunto atualizar baseado benefícios como compreensão concluído conhecimento conteúdo criar depois descreva descreve descrição deste desvantagens dificuldade document document documento encontrada encontradas escrever esse este estudado exemplo exemplos facilidade feito globais goback histórico index introdução modelo03 necessários objetivo objetivos oficial onclick para pode preciso principal produzi produzir referências requisitos resumo sacrificar semana site testar text title tópico write " },
{url: "docs/database/index.html", title: "Bancos de dados do projeto", text: "", tags: "111111111 123456789 222222222 987654321 agenda alterar após atualizado atualizar banco base básico boolean buscar buscar_medicos cliente clientes close commit conectado conectar conexao conexão connect consultar convenios convênios create criar crud cursor dados data date dbname delete document document dr_smith email encontrado está excluir excluir_medico exclusão execute exemplo exists fechar fetchall fetchone fornecidos from função hora hora_final hora_inicial host id_cliente id_convenio id_medico import incluir inserir inserir_medico insert instalação integer integracao integração into localhost login mail medico médico medico_id medicos médicos mkdir nodesequelize nome novamente nova_senha novo null observacoes observações operações pacotes para password primary print programa psycopg2 python read realizar references requisitos return returning saber script select senha senha123 serial seu_usuario site smith status sua_senha tabela tabelas table telefone text time title todos todos_medicos unique update usado user values varchar where with write " },
{url: "docs/index.html", title: "project.ph.app.br", text: "", tags: "abrangentes adequado adicionais adicional agenda ajudar aqui armazenar assistant atende atualização atualizados automatizadas banco cadastros chamadas cliente clientes coletar como comunicar conectado confirmação confirmações consultas contínua convênio convênios criar dados data detalhada document document documentação eficiência enviar equipe está estudar etapas fazer forma funcionamento garantir hora hora_final hora_inicial hospitais humanizados id_cliente id_convenio id_medico implementar informações integração interagir login mail manter manutenção medico médico medicos necessários nome número observações oferecer onde opção openai outras paciente para perguntas plano pode podemos preços preparar programa projeto quais realizar responde rotinas saber secretária segurança senha sistema site sobre status telefone testes textos title todas treinamento usado usar utilizar utilize validação virtual whatsapp write " },
{url: "docs/mapa_do_site.html", title: "Mapa do site", text: "", tags: "assistant bancos dados database document document documento frase markdown modelo openai palavras pesquisa printfooter project projeto site templates title write " },
{url: "docs/templates/modelo01.html", title: "Modelo 01 de documento markdown ", text: "", tags: "2021 adquirir agregar após assunto atualizar baseado benefícios como compreensão concluído conhecimento conteúdo criar depois descreva descreve descrição deste desvantagens dificuldade document document documento encontrada encontradas escrever esse este estudado exemplo exemplos facilidade feito globais goback histórico index introdução markdown modelo modelo03 necessários objetivo objetivos oficial onclick para pode preciso principal produzi produzir referências requisitos resumo sacrificar semana site testar text title tópico write " },
{url: "docs/tipue_results.html", title: "Pesquisa palavras ou frase no site", text: "", tags: "document document frase function palavra printfooter qual ready tipuesearch title write " },
{url: "mapa_do_site.html", title: "Mapa do site", text: "", tags: "assistant bancos dados database document document documento frase index markdown modelo openai palavras pesquisa printfooter project projeto python site templates title write " },
{url: "python/index.html", title: "Index Python", text: "", tags: "2021 adquirir agregar após assunto atualizar baseado benefícios como compreensão concluído conhecimento conteúdo criar depois descreva descreve descrição deste desvantagens dificuldade document document documento encontrada encontradas escrever esse este estudado exemplo exemplos facilidade feito globais goback histórico index introdução modelo03 necessários objetivo objetivos oficial onclick para pode preciso principal produzi produzir python referências requisitos resumo sacrificar semana site testar text title tópico write " }
  ]
};
