
    <div class="title"> <!-- inicio <div class="title"> -->
        <div style="display: table;width: 100%;">

            <div style="display: table-cell;width: 20%;">
                <!-- Logomarca-->
                <span>Blog.pssp.app.br</span> 
            </div>

            <div style="display: table-cell;width: 80%;">
                <!-- Título-->
                <span id="title">????????</span>
            </div>
        </div>
    </div> <!-- fim <div class="title"> -->