var tipuesearch = {
  pages: [
{url: "analise_de_sistemas/o_que_e_ddd.html", title: "O que é DDD ", text: "", tags: "0" },
{url: "comportamentos/anki/index.html", title: "Estudo do programa Anki ", text: "", tags: "1" },
{url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_0.2.html", title: "Hábitos que desejo adquirir em 2021 Versão: 0.2", text: "", tags: "2" },
{url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.0.html", title: "Hábitos que desejo adquirir em 2021 Versão: 1.1 - Data: 10/01/2021", text: "", tags: "3" },
{url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.2.html", title: "Hábitos que desejo adquirir em 2021 Versão: 1.2 - Data: 12/01/2021", text: "", tags: "4" },
{url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.3.html", title: "Hábitos que desejo adquirir em 2021 Versão: 1.3 - Data: 19/01/2021", text: "", tags: "5" },
{url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.4.html", title: "Hábitos que desejo adquirir em 2021 Versão: 1.4 - Data: 27/01/2021", text: "", tags: "6" },
{url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.5.html", title: "Hábitos que desejo adquirir em 2021 Versão: 1.5 - Data: 27/01/2021", text: "", tags: "7" },
{url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.6.2.html", title: "**Hábitos que desejo adquirir em 2021 Versão: 1.6.2 - Data: 21/03/2021**", text: "", tags: "8" },
{url: "comportamentos/habitos/2021/habitos_que_desejo_cultivar_versao_1.6.3.html", title: "**Hábitos que desejo adquirir em 2021 Versão: 1.6.3 - Data: 29/05/2021**", text: "", tags: "9" },
{url: "comportamentos/habitos/2022/Cinco_dicas_do_filme_o_poder_alem_da_vida.html", title: "Cinco Dicas do filme 'O poder além da vida' ", text: "", tags: "10" },
{url: "comportamentos/habitos/2022/Cinco_dicas_para_relacionamentos_saudaveis.html", title: "Cinco Dicas Para Relacionamentos Saudáveis | Momentos Cury", text: "", tags: "11" },
{url: "comportamentos/habitos/2022/janelas_da_memoria.html", title: "As Janelas da Memória", text: "", tags: "12" },
{url: "comportamentos/habitos/2022/Pedir a Deus que me dê uma forma de sobreviver em uma atividade que me de prazer.html", title: "Pedir a Deus que me dê uma forma de sobreviver em uma atividade que me dê prazer", text: "", tags: "13" },
{url: "comportamentos/poemas/mulher_eremita.html", title: "MULHER HEREMITA", text: "", tags: "14" },
{url: "comportamentos/psicologia/diferenca_entre_manipular_e_influenciar.html", title: "**Manipulação psicológica (Manipulação psicológica)**", text: "", tags: "15" },
{url: "comportamentos/psicologia/jamelas_da_memoria.html", title: "As Janelas da Memória", text: "", tags: "16" },
{url: "gestao_de_pessoas/crencas_limitadoras/2020-12-02-reflexão-minhas-crenças-limitadoras-em-2016.html", title: "Minhas crenças limitadoras em 2016", text: "", tags: "27" },
{url: "Hidraulica/estudo_relacao_aumento_ pressao_diametro_do_cano.html", title: "Estudar qual a relação do aumento de pressão e diâmetro do cano", text: "", tags: "28" },
{url: "historico.html", title: "Histórico das ocorrência do Blog ", text: "", tags: "29" },
{url: "index.html", title: "Home - Blog.pssp.app.br - em permanente construção. 🚧", text: "", tags: "30" },
{url: "index_tree.html", title: "Mapa do site", text: "", tags: "31" },
{url: "infraestrutura/androide/O_que_e_android_studio.html", title: "Modelo 03 de documento markdown ", text: "", tags: "32" },
{url: "infraestrutura/linux/banco_de_dados/mariadb/configurar.html", title: "_CONFIGURAÇÃO DO MARIADB_", text: "", tags: "33" },
{url: "infraestrutura/linux/banco_de_dados/mariadb/configurarmariadb.html", title: "CONFIGURAÇÃO DO MARIADB", text: "", tags: "34" },
{url: "infraestrutura/linux/banco_de_dados/mariadb/exemplos.html", title: "EXEMPLOS DE USO DO BANCO DE DADOS MARIADB ", text: "", tags: "35" },
{url: "infraestrutura/linux/banco_de_dados/mariadb/index.html", title: "Banco de dados Mariadb", text: "", tags: "36" },
{url: "infraestrutura/linux/banco_de_dados/mariadb/instalar.html", title: "COMO INSTALAR DO BANCO DE DADOS MARIADB ", text: "", tags: "37" }
  ]
};
