        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="description"   content="" />
        <meta name="keywords" content="" />

        <!-- CSS markdown  -->
        <link type="text/css" href="/css/defaultthemeMarkdown.css"  rel="stylesheet"/>
            
        <!-- CSS da página /index.html -->
        <link type="text/css" href="/css/defaulttheme.css" rel="stylesheet"/>
        <script type="application/x-javascript" src="/js/generic.js"></script>
        <script type="application/x-javascript" src="/js/tgeneric.js"></script>
